bot:
    # The bot token from https://discord.com/developers/applications
    token: "add-your-token-here"

    # Your Discord server's ID.
    server-id: 000000000000000000

    # Prefix for discord commands.
    prefix: "+"

    # Decides what messages are shown in console
    # Possible values are: Critical, Error, Warning, Information, Debug.
    log-level: "Information"

    # Sets the type of activity for the bot to display in its presence status when the server is offline
    # Possible values are: Playing, Streaming, ListeningTo, Watching, Competing
    presence-type: "Watching"

    # Sets the activity text shown in the bot's status.
    presence-text: "for server startup..."

# Sets command permissions for roles, affects the /server and /ra commands.
# The permissions use regex so "pbc.*" will allow using the pbc command with any arguments while "pbc Karl.*"
# will only allow people to use the command if the first argument starts with Karl.
# You can use 0 for the @everyone role
permissions:
    # Everyone
    000000000000000000:
        - "hello"
    # Moderator
    111111111111111111:
        - "pbc.*"
        - "bc.*"
    # Admin
    222222222222222222:
        - "pbc.*"
        - "bc.*"
        - "softrestart"
        - "restartnextround"

plugin:
    # Host to listen on, localhost by default. Try changing this to "0.0.0.0" (all addresses available) if the plugin isn't able to connect, some windows setups don't seem to work with a set address to listen on.
    # In case you want server to listen on something other than "127.0.0.1", make sure your firewall rules are correct so any outside connections are blocked to the port.
    address: "127.0.0.1"

    # Port to listen on, this has to be the same as the "bot port" in the plugin config and all bots you run have to have different ports or they will clash.
    port: 8888