
############# SCPDiscord configuration file #############


# Connection settings, the port cannot be the same as the SCPSL server port.
bot:
    ip: "127.0.0.1"
    port: 8888

settings:
    # The language is the same as the name of the language file you want to use.
    # Included language files: english (default), russian, french, polish, italian, finnish, english-emote, russian-emote, french-emote, polish-emote, finnish-emote
    language: "english"
    # Whether or not to show this server's player count in the bot's activity.
    # Set to false to disable.
    playercount: true
    # The message timestamp, see syntax guide here: https://docs.microsoft.com/en-us/previous-versions/dotnet/netframework-3.0/8kb3ddd4(v=vs.85)
    # Set to "" to disable.
    timestamp: "HH:mm:ss"
    # Whether or not the plugin should send more detailed console messages
    # Set to true to turn on.
    verbose: false
    # Whether or not the plugin should send debug information in the console
    # Set to true to turn on.
    debug: false
    # Turns on the config validation which shows the values after they have been read by the plugin so you can see they are correct
    configvalidation: false
    # Whether or not to use the rolesync system
    rolesync: true
    # Show that this server is using SCPDiscord using invisible text on Kigen's server list (https://kigen.co/scpsl/browser.php?table=y)
    # This is just used to count how many servers are running the plugin, but you may hide your server by setting this to false:
    metrics: true
    # Whether files should be read from the global config directory or the local one (aka the server specific one).
    useglobaldirectory:
        language: true
        rolesync: true
    # Always replace language files when the plugin starts, use this if you do not edit the language files and want to keep them up to date automatically (does not affect overrides.yml)
    regeneratelanguagefiles: true

# Sets commands which are run whenever someone with a synced Discord rank joins the server, only the highest one in the list that matches the player is executed
# Valid variables:
# steamid
# userid
# playerid
# name
# ipaddress
# discorddisplayname
# discordusername
# discordusernamewithdiscriminator
# discordid
# Turn on debug above to see console feedback when the commands are used
rolesync:
    - "add-role-id-here":
        - "scpd_grantvanillarank <var:userid> moderator"
        - "scpd_grantreservedslot <var:userid> <var:discordusernamewithdiscriminator> (<var:discordid>)"
        - "/pbc <var:playerid> 3 Moderator role synced from Discord."
    - "add-another-role-id-here":
        - "scpd_grantvanillarank <var:userid> donator"
        - "scpd_grantreservedslot <var:userid> <var:discordusernamewithdiscriminator> (<var:discordid>)"
        - "/pbc <var:playerid> 3 Donator role synced from Discord."
    - "add-everyone-role-id-here":
        - "scpd_removereservedslot <var:userid>"

# Name your channels here, this name is used in the channels section below. The left value is a name of your choice and the right is a channel id you want it to represent.
channels:
    - "default": "add-channel-id-here"
    - "staff": "add-channel-id-here"

channelsettings:
    # Removes online players' IPs from discord messages in the following channels
    # Set to [] to disable
    filterips: [ "default" ]
    # Replaces online players' SteamIDs with PlayerIDs in discord messages in the following channels
    # Set to [] to disable
    filtersteamids: []

# Using the channel aliases above you can direct events to different channels here
# Set to [] to disable an event.
messages:
    # Server events
    connectedtobot: [ "default", "staff" ]
    onroundstart: []
    onconnect: []
    onplayerleave: [ "default" ]
    onroundend: [ "default", "staff" ]
    onwaitingforplayers: [ "default" ]
    onroundrestart: [ "default", "staff" ]
    onsetservername: []
    onban:
        player: [ "default" ]
        server: [ "default" ]
    onbanissued:
        ip: [ "staff" ]
        userid: [ "staff" ]
    onbanupdated:
        ip: []
        userid: []
    onbanrevoked:
        ip: [ "staff" ]
        userid: [ "staff" ]
    onkick:
        player: [ "default", "staff" ]
        server: [ "default", "staff" ]
    onplayermuted:
        intercom: [ "default", "staff" ]
        standard: [ "default", "staff" ]
    onplayerunmuted:
        intercom: [ "default", "staff" ]
        standard: [ "default", "staff" ]
    oncallcommand:
        remoteadmin:
            player: []
            server: []
        game:
            player: []
            server: []
        console:
            player: []
            server: []
    onexecutedcommand:
        remoteadmin:
            player: [ "staff" ]
            server: [ "staff" ]
        game:
            player: [ "staff" ]
            server: [ "staff" ]
        console:
            player: [ "staff" ]
            server: [ "staff" ]

    # Environment events
    onscp914activate: []
    onstartcountdown:
        player:
            initiated: [ "default" ]
            resumed: [ "default" ]
        server:
            initiated: [ "default" ]
            resumed: [ "default" ]
    onstopcountdown:
        default: [ "default" ]
        noplayer: [ "default" ]
    ondetonate: [ "default" ]
    ondecontaminate: [ "default" ]
    onsummonvehicle:
        chaos: [ "default" ]
        mtf: [ "default" ]
    ongeneratorfinish: [ "default" ]
    onelevatoruse: []

    ongeneratorunlock: [ "default" ]
    ongeneratoropen: []
    ongeneratorclose: []
    ongeneratoractivated: [ "default" ]
    ongeneratordeactivated: [ "default" ]
    onscp914changeknob: []
    onplayertriggertesla:
        default: []
        ignored: []
    onpocketdimensionexit: [ "default" ]
    onpocketdimensionenter: [ "default" ]
    ondooraccess:
        allowed: []
        denied: []

    # SCP Events
    on079lockdoor: []
    on079elevator:
        up: []
        down: []
    on079teslagate: []
    on079addexp: []
    on079levelup: [ "default" ]
    on079unlockdoor: []
    on079lockdown: []
    on079cancellockdown: []
    onrecallzombie: []
    onplayerinfected: [ "default" ]

    # Player events
    onplayerhurt:
        default: []
        friendlyfire: []
        noattacker: []
    onplayerdie:
        default: [ "default" ]
        friendlyfire: [ "default", "staff" ]
        nokiller: [ "default" ]
    onplayerpickupitem: []
    onplayerpickupammo: []
    onplayerpickuparmor: []
    onplayerpickupscp330: []
    onplayerdropitem: []
    onplayerdropammo: []
    onplayerjoin: [ "default", "staff" ]
    onnicknameset: []
    onsetrole:
        roundstart: [ "default" ]
        latejoin: [ "default" ]
        respawn: [ "default" ]
        died: []
        escaped: [ "default" ]
        revived: [ "default" ]
        remoteadmin: [ "default" ]
        left: []
        other: []
    onspawn: []
    onthrowprojectile: [ "default", "staff" ]
    onspawnragdoll: []
    onitemuse: [ "default" ]
    onhandcuff:
        default: [ "default" ]
        nootherplayer: [ "default" ]
    onhandcuffremoved:
        default: [ "default" ]
        nootherplayer: [ "default" ]
    onplayerradioswitch: []
    onreload: []
    ongrenadeexplosion: []
    ongrenadehitplayer: []
    onteamrespawn:
        mtf: [ "default" ]
        ci: [ "default" ]